server:
  port: 8081

spring:
  application:
    name: TRAINING-SESSION-NOTIFICATION
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true